# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: cluster-api-provider-packet-
# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: infrastructure-packet
bases:
- crd
#- webhook # Disable this if you're not using the webhook functionality.
- default
images:
- name: docker.io/packethost/cluster-api-provider-packet:e2e # images with this name
  newTag: v0.4.0 # {"type":"string","x-kustomize":{"setter":{"name":"image-tag","value":"v0.4.0"}}}
  newName: docker.io/packethost/cluster-api-provider-packet # and this name
